[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Larmor Instrument Manual"
authors = [{name = "Larmor Team", email = "larmorinstrument@g"}]
dynamic = ["version", "description"]
