[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Larmor-Insturment-Manual"
authors = [{name = "Larmor Instrument Team", email = "LarmorInstrument@g"}]
dynamic = ["version", "description"]
